#!/bin/bash
# Quick setup on a fresh install of Ubuntu (16.04) with the programs I normally use

cd ~
sudo apt-get -y install vim zsh htop curl tmux vagrant virtualbox git
curl https://raw.githubusercontent.com/rasheedja/dotfiles/master/vim/vimrc > ~/.vimrc
curl https://raw.githubusercontent.com/rasheedja/dotfiles/master/zsh/zshrc > ~/.zshrc
curl -L git.io/antigen > ~/.antigen.zsh
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts
chsh -s $(which zsh)
