# Start antigen
source /usr/share/zsh/share/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles 
antigen bundle command-not-found
antigen bundle common-aliases 
antigen bundle cp
antigen bundle git
antigen bundle node
antigen bundle npm
antigen bundle nvm
antigen bundle pip
antigen bundle python
antigen bundle rsync
antigen bundle tmux
antigen bundle virtualenv
antigen bundle yarn

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

# Load the theme.
antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train

BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  custom
  dir
  git
  cmd_exec_time
)

# Finish antigen
antigen apply

# Aliases
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"

