# Start antigen
source ~/.antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Load bundles 
antigen bundle command-not-found
antigen bundle common-aliases 
antigen bundle cp
antigen bundle direnv
antigen bundle git
antigen bundle node
antigen bundle npm
antigen bundle nvm
antigen bundle pip
antigen bundle python
antigen bundle rsync
antigen bundle tmux
antigen bundle virtualenv
antigen bundle yarn

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

# Load the theme.
# antigen theme https://github.com/caiogondim/bullet-train-oh-my-zsh-theme bullet-train
antigen theme robbyrussell

BULLETTRAIN_PROMPT_ORDER=(
  time
  status
  custom
  dir
  git
  cmd_exec_time
)

# Finish antigen
antigen apply

# Specify default shell
SHELL=$(which zsh)

# Aliases
alias vimrc="vim ~/.vimrc"
alias zshrc="vim ~/.zshrc"

# Export TERM
export TERM=xterm-256color

# Add home opt to path
path+=('/home/junaid/opt')

# Add GPS to path
path+=('/home/junaid/Research/opt/GNAT/2018/bin')

# Add Isabelle to path
path+=('/home/junaid/Research/opt/Isabelle2018/bin')

# Add local bin
path+=('/home/junaid/.local/bin')

# Add ghcup to path
path+=('/home/junaid/.ghcup/bin')

# Add cabal bin to path
path+=('/home/junaid/.cabal/bin')

# direnv hook
eval "$(direnv hook zsh)"

